<a href="https://colab.research.google.com/github/Fowjaelahamed/Numpy/blob/master/MatrixBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loading Numpy Library

In [0]:
import numpy as np

# Matrix Operations

In [15]:
a = np.array([[1,2,3],[2,3,4],[5,6,7]])
b = np.array([[3,4,5],[6,7,8],[9,10,11]])
a + b

array([[ 4,  6,  8],
       [ 8, 10, 12],
       [14, 16, 18]])

In [16]:
a - b

array([[-2, -2, -2],
       [-4, -4, -4],
       [-4, -4, -4]])

In [17]:
a * b  #this will like as normal multiplication 

array([[ 3,  8, 15],
       [12, 21, 32],
       [45, 60, 77]])

In [18]:
a / b

array([[0.33333333, 0.5       , 0.6       ],
       [0.33333333, 0.42857143, 0.5       ],
       [0.55555556, 0.6       , 0.63636364]])

In [19]:
a % b

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [20]:
a = np.array([[2,3],[1,4]])
b = np.array([[6,4],[7,5]])
print(a.dot(b))  #dot() is used for actual matrix multiplication where m*n for a and p*q for b and it is possible for multiplication if n = q. 
print("-------")
print(b.dot(a))

[[33 23]
 [34 24]]
-------
[[16 34]
 [19 41]]


In [21]:
np.dot(a,b) #it also same as dot() function.

array([[33, 23],
       [34, 24]])

# many unary operations are allowed on those numpy arrays such as -
* **sum()** 
* **max()**
* **min()**
* **mean()**
* **std()**
* **cumsum()**

In [22]:
c = np.arange(12).reshape(3,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
print("sum of elements:",a.sum())
print("max of elements:",a.max())
print("min of elements:",a.min())
print("mean of elements:",a.mean())
print("standard Deviation of elements:",a.std())

sum of elements: 10
max of elements: 4
min of elements: 1
mean of elements: 2.5
standard Deviation of elements: 1.118033988749895


In [24]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
c.shape

(3, 4)

In [30]:
c.sum(axis=0) #it sums first column and make first value then sums second column and make second value and so on.

array([12, 15, 18, 21])

In [31]:
c.sum(axis=1) #it sums first row and make first value then sums second row and then make second value and so on.

array([ 6, 22, 38])

In [32]:
c.cumsum(axis=1) #it is cumulatitive sum of axis 1 .

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# Universal Functions
 * exp() ,sqrt() ,random.randn() , argmax() , max() ,argmin() ,argsort() , ceil() , corrcoef() , cov() ,cross() , cumprod() , cumsum() , diff() ,dot() , floor() ,inner(), inv() ,max() ,maximum(), mean(), median(), min() , minimum(), nonzero(), outer(), prod() ,re() ,round( ) , sort(), std(), sum() ,trace(), tranpose() , var() ,vdot() ,vectorise() 

In [33]:
np.exp(c)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [34]:
np.sqrt(c)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [35]:
np.random.randn(4,3)

array([[-0.69029324, -0.16754233, -0.02450388],
       [-0.05072562, -2.0783898 , -1.10321284],
       [ 0.01736425,  0.51984014,  1.256316  ],
       [ 1.34229969, -0.06737117, -0.40757438]])

In [40]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
np.argmax(c)

11

In [39]:
np.argmax(c,axis=0)

array([2, 2, 2, 2])

In [38]:
np.argmax(c,axis=1)

array([3, 3, 3])

# indexing, Slicing and Iterating
* 1D arrays can be indexed,sliced and iterated just like lists and tuples in python.

In [0]:
m = np.linspace(1,10,15)

In [44]:
m

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [45]:
m[2]

2.2857142857142856

In [46]:
m[2:5]

array([2.28571429, 2.92857143, 3.57142857])

In [0]:
m[:6:2] = 100 #here value from 0 to 5 and its step is 2 and changing value will be 100.

In [50]:
m

array([100.        ,   1.64285714, 100.        ,   2.92857143,
       100.        ,   4.21428571,   4.85714286,   5.5       ,
         6.14285714,   6.78571429,   7.42857143,   8.07142857,
         8.71428571,   9.35714286,  10.        ])

In [51]:
m[::-1]

array([ 10.        ,   9.35714286,   8.71428571,   8.07142857,
         7.42857143,   6.78571429,   6.14285714,   5.5       ,
         4.85714286,   4.21428571, 100.        ,   2.92857143,
       100.        ,   1.64285714, 100.        ])

In [53]:
m # it's value changed because of line number 49.

array([100.        ,   1.64285714, 100.        ,   2.92857143,
       100.        ,   4.21428571,   4.85714286,   5.5       ,
         6.14285714,   6.78571429,   7.42857143,   8.07142857,
         8.71428571,   9.35714286,  10.        ])

* **Multi-Dimensional arrays** can have one index per axis.those indices are given in a tuple sperated by comma.

In [0]:
n = np.arange(20).reshape(5,4)

In [55]:
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [58]:
n.shape

(5, 4)

In [60]:
n[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [61]:
n[2,3]

11

In [62]:
n[0:3,1]

array([1, 5, 9])

In [65]:
n[:,1]

array([ 1,  5,  9, 13, 17])

In [66]:
n[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
n[1:3,...]  #here ... works as : it works as previous step.

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
n[-1]

array([16, 17, 18, 19])

In [71]:
p = np.arange(45).reshape(3,3,5)
p

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [74]:
p.shape

(3, 3, 5)

In [72]:
p[1]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [73]:
p[1,1:,1:3]

array([[21, 22],
       [26, 27]])

In [76]:
p[2,0:,3:]

array([[33, 34],
       [38, 39],
       [43, 44]])

* **Iterating ** over mutli-dimensional array

In [77]:
p

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [81]:
for axis0 in p:
  print("*" * 10)
  for axis1 in axis0:
    print(axis1)
    print("-" * 10)

**********
[0 1 2 3 4]
----------
[5 6 7 8 9]
----------
[10 11 12 13 14]
----------
**********
[15 16 17 18 19]
----------
[20 21 22 23 24]
----------
[25 26 27 28 29]
----------
**********
[30 31 32 33 34]
----------
[35 36 37 38 39]
----------
[40 41 42 43 44]
----------


In [84]:
for i in range(3):
  print("Department ",i)
  print("----------")
  for j in range(3):
    print("Employee ",j)
    print(p[i,j])

Department  0
----------
Employee  0
[0 1 2 3 4]
Employee  1
[5 6 7 8 9]
Employee  2
[10 11 12 13 14]
Department  1
----------
Employee  0
[15 16 17 18 19]
Employee  1
[20 21 22 23 24]
Employee  2
[25 26 27 28 29]
Department  2
----------
Employee  0
[30 31 32 33 34]
Employee  1
[35 36 37 38 39]
Employee  2
[40 41 42 43 44]


In [85]:
p.flat

In [86]:
for em in p.flat:
  print(em)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44


# shape manipulation
**changing shape of an array**

In [101]:
l = np.floor(18*np.random.randn(3,4))
print(l)
print(l.shape)

[[-30.  -5.   2.  -8.]
 [ 38. -11.  14. -13.]
 [-22.  34.  -6.  22.]]
(3, 4)


In [102]:
l.ravel() #it will return the list

array([-30.,  -5.,   2.,  -8.,  38., -11.,  14., -13., -22.,  34.,  -6.,
        22.])

In [103]:
l.ravel().reshape(6,2)

array([[-30.,  -5.],
       [  2.,  -8.],
       [ 38., -11.],
       [ 14., -13.],
       [-22.,  34.],
       [ -6.,  22.]])

In [104]:
l.T #it will be transition matrix means row  will be column and column will be row

array([[-30.,  38., -22.],
       [ -5., -11.,  34.],
       [  2.,  14.,  -6.],
       [ -8., -13.,  22.]])

In [105]:
l

array([[-30.,  -5.,   2.,  -8.],
       [ 38., -11.,  14., -13.],
       [-22.,  34.,  -6.,  22.]])

In [106]:
l.shape

(3, 4)

In [0]:
l.resize(2,6) #resize() using this the matrix shape will be changed but in reshape() we see thatmain matrix shape don't change when we reshape but in resize () it will happen. 

In [108]:
l # so the shape of l changed permanantly

array([[-30.,  -5.,   2.,  -8.,  38., -11.],
       [ 14., -13., -22.,  34.,  -6.,  22.]])

In [109]:
l.shape

(2, 6)